version: '3'

services:
  eureka-client-two:
    build: .
    hostname: eureka-client-two
    ports:
      - 18002:18002
    environment:
      - INSTANCE_HOST=192.168.0.104
      - EUREKA_SERVER_URL=http://192.168.0.104:18761/eureka/
